export type BlogsActionType = 'GETTING_ALL_BLOGS' | 'GETTING_ALL_BLOGS_SUCCESS' | 'GETTING_ALL_BLOGS_FAILURE';

const GETTING_ALL_BLOGS: BlogsActionType = 'GETTING_ALL_BLOGS';
const GETTING_ALL_BLOGS_SUCCESS: BlogsActionType = 'GETTING_ALL_BLOGS_SUCCESS';
const GETTING_ALL_BLOGS_FAILURE: BlogsActionType = 'GETTING_ALL_BLOGS_FAILURE';

export {GETTING_ALL_BLOGS, GETTING_ALL_BLOGS_SUCCESS, GETTING_ALL_BLOGS_FAILURE};
