export type BlogsActionType =
    | 'GETTING_BLOG_DETAILS'
    | 'GETTING_BLOG_DETAILS_SUCCESS'
    | 'GETTING_BLOG_DETAILS_FAILURE'
    | 'GETTING_ALL_BLOGS'
    | 'GETTING_ALL_BLOGS_SUCCESS'
    | 'GETTING_ALL_BLOGS_FAILURE'
    | 'DELETING_BLOG'
    | 'DELETING_BLOG_SUCCESS'
    | 'DELETING_BLOG_FAILURE';

const GETTING_ALL_BLOGS: BlogsActionType = 'GETTING_ALL_BLOGS';
const GETTING_ALL_BLOGS_SUCCESS: BlogsActionType = 'GETTING_ALL_BLOGS_SUCCESS';
const GETTING_ALL_BLOGS_FAILURE: BlogsActionType = 'GETTING_ALL_BLOGS_FAILURE';

const GETTING_BLOG_DETAILS: BlogsActionType = 'GETTING_BLOG_DETAILS';
const GETTING_BLOG_DETAILS_SUCCESS: BlogsActionType = 'GETTING_BLOG_DETAILS_SUCCESS';
const GETTING_BLOG_DETAILS_FAILURE: BlogsActionType = 'GETTING_BLOG_DETAILS_FAILURE';

const DELETING_BLOG: BlogsActionType = 'DELETING_BLOG';
const DELETING_BLOG_SUCCESS: BlogsActionType = 'DELETING_BLOG_SUCCESS';
const DELETING_BLOG_FAILURE: BlogsActionType = 'DELETING_BLOG_FAILURE';

export {
    GETTING_ALL_BLOGS,
    GETTING_ALL_BLOGS_SUCCESS,
    GETTING_ALL_BLOGS_FAILURE,
    GETTING_BLOG_DETAILS,
    GETTING_BLOG_DETAILS_SUCCESS,
    GETTING_BLOG_DETAILS_FAILURE,
    DELETING_BLOG,
    DELETING_BLOG_SUCCESS,
    DELETING_BLOG_FAILURE,
};
