export type UsersActionType =
    | 'GETTING_PROFILE_DETAILS'
    | 'GETTING_PROFILE_DETAILS_SUCCESS'
    | 'GETTING_PROFILE_DETAILS_FAILURE'
    | 'GETTING_ALL_USERS'
    | 'GETTING_ALL_USERS_SUCCESS'
    | 'GETTING_ALL_USERS_FAILURE'
    | 'LOGGING_IN'
    | 'LOGGING_IN_SUCCESS'
    | 'LOGGING_IN_FAILURE'
    | 'CREATING_USER'
    | 'CREATING_USER_SUCCESS'
    | 'CREATING_USER_FAILURE'
    | 'LOGGING_OUT'
    | 'LOGGING_OUT_SUCCESS'
    | 'LOGGING_OUT_FAILURE'
    | 'DELETING_USER'
    | 'DELETING_USER_SUCCESS'
    | 'DELETING_USER_FAILURE';

const GETTING_PROFILE_DETAILS: UsersActionType = 'GETTING_PROFILE_DETAILS';
const GETTING_PROFILE_DETAILS_SUCCESS: UsersActionType = 'GETTING_PROFILE_DETAILS_SUCCESS';
const GETTING_PROFILE_DETAILS_FAILURE: UsersActionType = 'GETTING_PROFILE_DETAILS_FAILURE';

const GETTING_ALL_USERS: UsersActionType = 'GETTING_ALL_USERS';
const GETTING_ALL_USERS_SUCCESS: UsersActionType = 'GETTING_ALL_USERS_SUCCESS';
const GETTING_ALL_USERS_FAILURE: UsersActionType = 'GETTING_ALL_USERS_FAILURE';

const LOGGING_IN: UsersActionType = 'LOGGING_IN';
const LOGGING_IN_SUCCESS: UsersActionType = 'LOGGING_IN_SUCCESS';
const LOGGING_IN_FAILURE: UsersActionType = 'LOGGING_IN_FAILURE';

const CREATING_USER: UsersActionType = 'LOGGING_IN';
const CREATING_USER_SUCCESS: UsersActionType = 'LOGGING_IN_SUCCESS';
const CREATING_USER_FAILURE: UsersActionType = 'LOGGING_IN_FAILURE';

const LOGGING_OUT: UsersActionType = 'LOGGING_OUT';
const LOGGING_OUT_SUCCESS: UsersActionType = 'LOGGING_OUT_SUCCESS';
const LOGGING_OUT_FAILURE: UsersActionType = 'LOGGING_OUT_FAILURE';

const DELETING_USER: UsersActionType = 'DELETING_USER';
const DELETING_USER_SUCCESS: UsersActionType = 'DELETING_USER_SUCCESS';
const DELETING_USER_FAILURE: UsersActionType = 'DELETING_USER_FAILURE';

export {
    GETTING_PROFILE_DETAILS,
    GETTING_PROFILE_DETAILS_SUCCESS,
    GETTING_PROFILE_DETAILS_FAILURE,
    GETTING_ALL_USERS,
    GETTING_ALL_USERS_SUCCESS,
    GETTING_ALL_USERS_FAILURE,
    LOGGING_IN,
    LOGGING_IN_SUCCESS,
    LOGGING_IN_FAILURE,
    CREATING_USER,
    CREATING_USER_SUCCESS,
    CREATING_USER_FAILURE,
    LOGGING_OUT,
    LOGGING_OUT_SUCCESS,
    LOGGING_OUT_FAILURE,
    DELETING_USER,
    DELETING_USER_SUCCESS,
    DELETING_USER_FAILURE,
};
